- name: Create a command
  hosts: localhost
  connection: local
  tasks:
    - name: shell command
      ansible.builtin.shell: "date"
      register: out
    - name: display the output
      ansible.builtin.debug:
        msg: "{{out}}"