---
- name: create the user
  hosts: localhost
  connection: local
  tasks:
    - name: User creation
      ansible.builtin.user:
        name: anki
        password: masterclass
        uid: 12342
      register: out
    - name: detailed info
      ansible.builtin.debug:
        msg: "{{out}}"
...