---
- name: create the user
  hosts: localhost
  connection: local
  tasks:
    - name: User creation
      ansible.builtin.user:
        name: anki
        password: massraabacha
        uid: 12342
...