---
- name: create the user
  hosts: localhost
  connection: local
  tasks:
    - name: User creation
      ansible.builtin.file:
        name: /etc/anki
        state: touch
      register: out
    - name: detailed info
      ansible.builtin.debug:
        var: out
...