- name: Change the file
  hosts: localhost
  connection: local
  tasks:
    - name: copy the file
      ansible.builtin.git:
        repo: https://github.com/BalaAnkiReddy-jinkala/LearnAnsible.git
        dest: /opt/repo
      register: out
    - name: check the url is reached
      ansible.builtin.debug:
        var: out