- name: Change the file
  hosts: localhost
  connection: local
  tasks:
    - name: copy the file
      ansible.builtin.dnf:
        name: apache2
        state: present
    - name: restart the service
      ansible.builtin.service:
        name: apache2
        state: restarted
