- name: include
  hosts: localhost
  connection: local
  tasks:
    - name: module
      ansible.builtin.include:
        - git pull ;ansible-playbook -i inv 01sample.yml
        - git pull ;ansible-playbook -i inv 02sample.yml
        - git pull ;ansible-playbook -i inv 03sample.yml
        - git pull ;ansible-playbook -i inv 04sample.yml
      register: out
    - name: display
      ansible.builtin.debug:
        var: out