- name: Include and Execute Playbooks
  hosts: localhost
  connection: local
  tasks:
    - name: Pull latest code from Git
      ansible.builtin.shell: git pull
      register: git_output

    - name: Display Git output
      ansible.builtin.debug:
        var: git_output.stdout

    - name: Run playbooks sequentially
      ansible.builtin.include: ansible-playbook -i inv {{ item }}
      with_items:
        - 01sample.yml
        - 02sample.yml
        - 03sample.yml
        - 04sample.yml
      register: playbook_output

    - name: Display playbook execution results
      ansible.builtin.debug:
        var: playbook_output
