- name: play variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: display the output
      ansible.builtin.debug:
        msg: "{{URL}}"

- name: task variables
  hosts: localhost
  connection: local
  tasks:
    - name: display
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.google.com

- name: Print fact
  hosts: localhost
  connection: local
  tasks:
    - name: output
      ansible.builtin.debug:
        msg: "{{ansible_distraction}}"