- name: play variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: display the output
      ansible.builtin.debug:
        msg: "{{URL}}"

- name: task variables
  hosts: localhost
  connection: local
  tasks:
    - name: display
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.google.com

- name: Print fact
  hosts: localhost
  connection: local
  tasks:
    - name: print fact
      ansible.builtin.debug:
        msg: "{{ansible_distribution}}"

- name: Print the date and time
  hosts: localhost
  connection: local
  tasks:
    - name: display the opt-out
      ansible.builtin.shell: uptime
      register: anki
    - name: final format
      ansible.builtin.debug:
        var: anki