- name: error find out
  hosts: localhost
  connection: local
  tasks:
    - name: find the output
      ansible.builtin.shell: cat /etc/passwd | grep john
      register: out
      ignore_errors: yes
    - name: final process
      ansible.builtin.debug:
        msg: this john user is not there our system
      when : out.stdout == ""