- name: error find out
  hosts: localhost
  connection: local
  tasks:
    - name: find the output
      ansible.builtin.shell: cat /etc/passwd | grep anki
      register: hello
      ignore_errors: yes
    - name: final process
      ansible.builtin.debug:
        msg: "this anki user is not there our system"
      when : hello.stdout == ""